# Generated by Django 4.1.7 on 2023-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.CharField(max_length=12)),
                ('LeaveFrom', models.DateField()),
                ('LeaveTo', models.DateField()),
            ],
        ),
    ]
