# Generated by Django 4.1.7 on 2023-03-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('AvailDate', models.DateField(primary_key=True, serialize=False)),
                ('TotallLoanAmount', models.FloatField()),
                ('Tenor', models.IntegerField()),
                ('AmountPaid', models.FloatField()),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('EmpId', 'AvailDate'), name='unique_loan'),
        ),
    ]
