# Generated by Django 4.1.7 on 2023-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_loan_loan_unique_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='EmpId',
            field=models.CharField(max_length=12),
        ),
    ]
