# Generated by Django 4.1.7 on 2023-03-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_loan_empid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='TotallLoanAmount',
            new_name='TotalLoanAmount',
        ),
    ]
