# Generated by Django 4.1.7 on 2023-03-20 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_rename_totallloanamount_loan_totalloanamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PFTax', models.FloatField()),
                ('IncomeTax', models.FloatField()),
                ('BasicPay', models.FloatField()),
                ('HRA', models.FloatField()),
                ('Conveyance', models.FloatField()),
                ('Allowance', models.FloatField()),
                ('LossOfPay', models.FloatField()),
                ('LoanDeduction', models.FloatField()),
                ('FinalSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.UniqueConstraint(fields=('EmpId', 'LeaveFrom'), name='unique_leave'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('EmpId', 'EffectiveDate'), name='unique_progress'),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='EmpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='payhistory',
            unique_together={('EmpId', 'created_at')},
        ),
    ]
